"""FastAPI application providing streaming omni-modal generation."""
from __future__ import annotations

import base64
import io
import json
import time
from typing import Any, Dict, Iterator, Optional

import numpy as np
from fastapi import FastAPI
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field, field_validator

from web_stable_diffusion.models.miniturbo_omnimodal import BundleEvent, OmniModalMiniturbo


def _normalise_metadata(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _normalise_metadata(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_normalise_metadata(item) for item in value]
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, np.ndarray):
        return value.tolist()
    return value


def _event_payload(event: BundleEvent, array: np.ndarray) -> Dict[str, Any]:
    buffer = io.BytesIO()
    np.savez_compressed(buffer, payload=array)
    encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
    return {
        "type": "modality",
        "modality": event.key,
        "duration_s": event.duration_s,
        "completed": event.completed,
        "total": event.total,
        "progress": event.progress,
        "shape": list(array.shape),
        "dtype": str(array.dtype),
        "backend": event.result.backend,
        "device": event.result.device,
        "metadata": _normalise_metadata(event.result.metadata),
        "payload": encoded,
    }


class GenerateRequest(BaseModel):
    prompt: str = Field(..., min_length=1)
    resolution: int = Field(256, ge=16, le=1024)
    frames: int = Field(16, ge=1, le=256)
    volume_size: int = Field(32, ge=8, le=256)
    audio_length: int = Field(2048, ge=16, le=65536)
    executor: str = Field("auto")
    max_workers: Optional[int] = Field(None, ge=1)
    timeout: Optional[float] = Field(None, gt=0)

    @field_validator("executor")
    @classmethod
    def _validate_executor(cls, value: str) -> str:
        lowered = value.lower()
        if lowered not in {"auto", "thread", "process"}:
            raise ValueError("executor must be 'auto', 'thread', or 'process'")
        return lowered

    def generation_kwargs(self) -> Dict[str, Any]:
        return {
            "prompt": self.prompt,
            "resolution": self.resolution,
            "frames": self.frames,
            "volume_size": self.volume_size,
            "audio_length": self.audio_length,
            "executor": self.executor,
            "max_workers": self.max_workers,
            "timeout": self.timeout,
        }


def _stream_bundle_events(request: GenerateRequest) -> Iterator[str]:
    engine = OmniModalMiniturbo()
    total_wall = 0.0
    artifacts: Dict[str, Any] = {}
    start = time.perf_counter()

    try:
        for event in engine.generate_bundle_iter(**request.generation_kwargs()):
            array = event.result.to_numpy()
            payload = _event_payload(event, array)
            artifacts[event.key] = {
                "shape": list(array.shape),
                "dtype": str(array.dtype),
                "backend": event.result.backend,
                "device": event.result.device,
                "metadata": _normalise_metadata(event.result.metadata),
            }
            total_wall += event.duration_s
            yield json.dumps(payload) + "\n"
    except TimeoutError as exc:
        yield json.dumps({"type": "error", "message": str(exc)}) + "\n"
        return

    manifest = {
        "artifacts": artifacts,
        "metadata": {
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "metrics": {
                "wall_clock_s_total": total_wall,
                "wall_clock_s_elapsed": time.perf_counter() - start,
            },
        },
    }
    yield json.dumps({"type": "complete", "manifest": manifest}) + "\n"


def create_app() -> FastAPI:
    app = FastAPI(
        title="OmniModal Streaming API",
        description="Stream omni-modal artefacts generated by the NeuroSymbolic engine.",
        version="0.1.0",
    )

    @app.post("/generate", response_class=StreamingResponse)
    def generate(request: GenerateRequest) -> StreamingResponse:
        return StreamingResponse(
            _stream_bundle_events(request), media_type="application/jsonl"
        )

    return app


app = create_app()


__all__ = ["app", "create_app", "GenerateRequest"]
